#rememeber dockerfile needs to be 'Dockerfile' to work in terminal, not DOCKERFILE
# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy requirements first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the service files
COPY . .

# Expose the port that your FastAPI app will run on
EXPOSE 9001

# Command to run the FastAPI app when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9001"]