FROM python:3.10-slim

#sets work directory
WORKDIR /app

#install system dependencies
RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*

#copies the requirements from requirements.txt and installs them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#copies the app files
COPY . .

#exposes port
EXPOSE 9002

#runs Fast API with uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9002"]
